from db import DbConnection

conn = DbConnection.dbconn(self="")
c = conn.cursor()

sql = "SELECT TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'mm'),-1),'YYYYMM') TBNAME FROM DUAL";  
c.execute(sql)
for TBNAME in c:
    TableName = str(TBNAME[0])

#create so table from MI table
sql = "CREATE TABLE SALES_"+TableName+" AS "\
    "SELECT  REGION, PROVINCE, RTOM, CUSTOMER_REF,ACCOUNT_NUM, "\
       "PRODUCT_ID, CUST_ORDER_NUM, SUPPLIER_ORDER_NUM, EVENT_SOURCE, "\
       "SERO_ORDT_TYPE, BILLING_CENTRE, COST_CENTRE, TARIFF_ID, "\
       "TARIFF_NAME, BB_PACKAGE_NAME, PRODUCT_LABEL, BSSDSP, "\
       "MEDIUM, SALES_CHANNEL1, SALES_PERSON11, 'BB' COM_TYPE, "\
       "0  STATUS_STG1 "\
  "FROM REPO.BB_SLT_BB_SERVICE@DBLINK_GENEVA "\
 "WHERE     SALES_CHANNEL1 IN (SELECT DEALER_NAME FROM EX_DEALERS) "\
       "AND MEDIUM IN ('FTTH', 'COPPER') "\
       "AND SERO_ORDT_TYPE = 'CREATE' "\
" UNION "\
"SELECT  REGION, PROVINCE, RTOM, CUSTOMER_REF, ACCOUNT_NUM, PRODUCT_ID, "\
       "CUST_ORDER_NUM, SUPPLIER_ORDER_NUM, EVENT_SOURCE, SERO_ORDT_TYPE, "\
       "BILLING_CENTRE, COST_CENTRE, TARIFF_ID, TARIFF_NAME,BB_PACKAGE_NAME, "\
       "PRODUCT_LABEL, BSSDSP,  MEDIUM,SALES_CHANNEL1, SALES_PERSON11, "\
       "'BB' COM_TYPE,  0  STATUS_STG1 "\
  "FROM REPO.BB_SLT_BB_SERVICE@DBLINK_GENEVA "\
 "WHERE     SALES_CHANNEL1 IN (SELECT DEALER_NAME FROM EX_DEALERS) "\
       "AND MEDIUM = 'LTE' "\
       "AND SERO_ORDT_TYPE IN ('CREATE', 'CREATE-UPGRD SAME NO') "\
" UNION        "\
"SELECT  REGION, PROVINCE,  RTOM, CUSTOMER_REF, ACCOUNT_NUM, PRODUCT_ID, "\
       "CUST_ORDER_NUM, SUPPLIER_ORDER_NUM, EVENT_SOURCE, SERO_ORDT_TYPE, "\
       "BILLING_CENTRE, COST_CENTRE, TARIFF_ID,TARIFF_NAME, '', PRODUCT_LABEL, "\
      " BSSDSP, MEDIUM, SALES_CHANNEL1, SALES_PERSON11, 'LTE',0  STATUS_STG1 "\
  "FROM REPO.BB_SLT_BB_SERVICE@DBLINK_GENEVA "\
 "WHERE     SALES_CHANNEL1 IN (SELECT DEALER_NAME FROM EX_DEALERS) "\
      " AND MEDIUM = 'LTE' "\
      " AND SERO_ORDT_TYPE IN ('CREATE', 'CREATE-UPGRD SAME NO') "\
" UNION "\
"SELECT  REGION,PROVINCE, RTOM,CUSTOMER_REF, ACCOUNT_NUM,PRODUCT_ID, "\
      " CUST_ORDER_NUM, SUPPLIER_ORDER_NUM,EVENT_SOURCE,SERO_ORDT_TYPE, "\
      " BILLING_CENTRE, COST_CENTRE,TARIFF_ID,TARIFF_NAME, '',PRODUCT_LABEL, "\
     "  BSSDSP,MEDIUM,SALES_CHANNEL1,SALES_PERSON11,'MEGALINE',0     STATUS_STG1 "\
  "FROM REPO.V_SLT_VOICE_SERVICE@DBLINK_GENEVA "\
" WHERE     SALES_CHANNEL1 IN (SELECT DEALER_NAME FROM EX_DEALERS) "\
      " AND MEDIUM = 'COPPER' "\
      " AND SERO_ORDT_TYPE = 'CREATE' "\
" UNION "\
"SELECT  REGION, PROVINCE, RTOM,CUSTOMER_REF, ACCOUNT_NUM,PRODUCT_ID, CUST_ORDER_NUM, "\
       "SUPPLIER_ORDER_NUM, EVENT_SOURCE, SERO_ORDT_TYPE, BILLING_CENTRE,COST_CENTRE, "\
      " TARIFF_ID,TARIFF_NAME, '',PRODUCT_LABEL,BSSDSP, MEDIUM,SALES_CHANNEL1,SALES_PERSON11, "\
      " 'FTTH',  0     STATUS_STG1 "\
  "FROM REPO.V_SLT_VOICE_SERVICE@DBLINK_GENEVA "\
 "WHERE     SALES_CHANNEL1 IN (SELECT DEALER_NAME FROM EX_DEALERS) "\
      " AND MEDIUM = 'FTTH' "\
     "  AND SERO_ORDT_TYPE IN ('CREATE', 'CREATE-UPGRD SAME NO') "\
" UNION "\
" SELECT  REGION, PROVINCE, RTOM, CUSTOMER_REF, ACCOUNT_NUM, PRODUCT_ID, "\
       "CUST_ORDER_NUM, SUPPLIER_ORDER_NUM, EVENT_SOURCE,SERO_ORDT_TYPE,BILLING_CENTRE, "\
      " COST_CENTRE, TARIFF_ID, TARIFF_NAME, PEOTV_PACKAGE_NAME, PRODUCT_LABEL, "\
      " BSSDSP, MEDIUM, SALES_CHANNEL, SALES_PERSON, 'IPTV', 0     STATUS_STG1 "\
  "FROM REPO.E_SLT_PEOTV_SERVICE@DBLINK_GENEVA "\
 "WHERE     SALES_CHANNEL IN (SELECT DEALER_NAME FROM EX_DEALERS) "\
      " AND MEDIUM IN ('FTTH', 'COPPER') "\
     "  AND SERO_ORDT_TYPE = 'CREATE' "\
" UNION "\
" SELECT  A.REGION, A.PROVINCE, A.RTOM, A.CUSTOMER_REF, A.ACCOUNT_NUM, A.PRODUCT_ID, "\
       "A.CUST_ORDER_NUM, A.SUPPLIER_ORDER_NUM, A.EVENT_SOURCE,A.SERO_ORDT_TYPE,A.BILLING_CENTRE, "\
      " A.COST_CENTRE, A.TARIFF_ID, A.TARIFF_NAME, A.PEOTV_PACKAGE_NAME, A.PRODUCT_LABEL, "\
      " A.BSSDSP, A.MEDIUM, A.SALES_CHANNEL, A.SALES_PERSON, 'IPTV', 0     STATUS_STG1 "\
      " FROM REPO.E_SLT_PEOTV_SERVICE@DBLINK_GENEVA A ,SERVICE_ORDERS SO, CIRCUITS C , SERVICE_ORDER_ATTRIBUTES SOA"\
" WHERE A.SERO_ORDT_TYPE LIKE 'CREATE-UPGRD%'"\
" AND C.CIRT_DISPLAYNAME = ACCESS_PIPE_IDENTIFIER"\
" AND C.CIRT_NAME = SO.SERO_CIRT_NAME"\
" AND SO.SERO_ORDT_TYPE = A.SERO_ORDT_TYPE"\
" AND SO.SERO_STAS_ABBREVIATION = 'CLOSED'"\
" AND SOA.SEOA_SERO_ID = SO.SERO_ID"\
" AND SALES_CHANNEL IN (SELECT DEALER_NAME FROM EX_DEALERS) "\
" AND SOA.SEOA_NAME = 'TYPE OF MEGA TO FTTH MIGRATION'"\
" AND SOA.SEOA_DEFAULTVALUE IN ('SP to DP PEO','DP BB to TP','SP to TP') "\
" UNION "\
"SELECT  A.REGION, A.PROVINCE, A.RTOM, A.CUSTOMER_REF,A.ACCOUNT_NUM, "\
       "A.PRODUCT_ID, A.CUST_ORDER_NUM, A.SUPPLIER_ORDER_NUM, A.EVENT_SOURCE, "\
       "A.SERO_ORDT_TYPE, A.BILLING_CENTRE, A.COST_CENTRE, A.TARIFF_ID, "\
       "A.TARIFF_NAME, A.BB_PACKAGE_NAME, A.PRODUCT_LABEL, A.BSSDSP, "\
       "A.MEDIUM, A.SALES_CHANNEL1, A.SALES_PERSON11, 'BB' COM_TYPE, "\
       "0  STATUS_STG1 "\
" FROM REPO.BB_SLT_BB_SERVICE@DBLINK_GENEVA A ,SERVICE_ORDERS SO, CIRCUITS C , SERVICE_ORDER_ATTRIBUTES SOA"\
" WHERE A.SERO_ORDT_TYPE LIKE 'CREATE-UPGRD%'"\
" AND MEDIUM = 'FTTH'"\
" AND C.CIRT_DISPLAYNAME = ACCESS_PIPE_IDENTIFIER"\
" AND C.CIRT_NAME = SO.SERO_CIRT_NAME"\
" AND SO.SERO_ORDT_TYPE = A.SERO_ORDT_TYPE"\
" AND SO.SERO_STAS_ABBREVIATION = 'CLOSED'"\
" AND SOA.SEOA_SERO_ID = SO.SERO_ID"\
" AND  SALES_CHANNEL1 IN (SELECT DEALER_NAME FROM EX_DEALERS) "\
" AND SOA.SEOA_NAME = 'TYPE OF MEGA TO FTTH MIGRATION'"\
" AND SOA.SEOA_DEFAULTVALUE IN ('DP PEO to TP','SP to DP BB','SP to TP')"
#print(sql)
c.execute(sql)



c.execute("commit")
    
c.close()
conn.close()