from db import DbConnection
import pandas as pd

conn = DbConnection.dbconn(self="")
c = conn.cursor()

sql = "SELECT TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'mm'),-1),'YYYYMM') TBNAME FROM DUAL";  
c.execute(sql)
for TBNAME in c:
    TableName = str(TBNAME[0])

#REMOVE BLACKLIST PRICE PLANS
sql = "UPDATE SALES_202205 SET STATUS = 100 WHERE TARIFF_NAME IN (SELECT PRICEPLAN FROM EX_PRICEPLAN_BL )"
c.execute(sql)
c.execute("commit")

#GET ACTIVE DELER TABLE
sql = "SELECT TABLE_NAME  FROM EX_SETTING WHERE DISCRIPTION = 'DEALER' AND END_DATE IS NULL";  
c.execute(sql)
for TABLE_NAME in c:
    DealerTableName = str(TABLE_NAME[0]) 

#GET ACTIVE BB TABLE
sql = "SELECT TABLE_NAME  FROM EX_SETTING WHERE DISCRIPTION = 'COM_BB' AND END_DATE IS NULL";  
c.execute(sql)
for TABLE_NAME in c:
    BBTableName = str(TABLE_NAME[0]) 

#GET ACTIVE IPTV TABLE
sql = "SELECT TABLE_NAME  FROM EX_SETTING WHERE DISCRIPTION = 'COM_IPTV' AND END_DATE IS NULL";  
c.execute(sql)
for TABLE_NAME in c:
    IPTVTableName = str(TABLE_NAME[0]) 

#GET ACTIVE BEARER TABLE
sql = "SELECT TABLE_NAME  FROM EX_SETTING WHERE DISCRIPTION = 'COM_BEARER' AND END_DATE IS NULL";  
c.execute(sql)
for TABLE_NAME in c:
    BearerTableName = str(TABLE_NAME[0]) 

#GET ACTIVE SLAB TABLE
sql = "SELECT TABLE_NAME  FROM EX_SETTING WHERE DISCRIPTION = 'SALES_SLAB' AND END_DATE IS NULL";  
c.execute(sql)
for TABLE_NAME in c:
    SlabTableName = str(TABLE_NAME[0]) 

#CREATE SLAES COUNT TABLE
sql = "CREATE TABLE SALES_COUNT_"+TableName+" AS SELECT DEALER_NAME , COUNT (*) SALES_COUNT FROM "+DealerTableName+" , SALES_"+TableName+" WHERE DEALER_NAME = SALES_CHANNEL1 AND COM_TYPE IN ('MEGALINE' , 'LTE' , 'FTTH') AND DEALER_TYPE = 'M' AND STATUS = 0 GROUP BY DEALER_NAME UNION SELECT SALES_PERSON11 , COUNT (*) FROM "+DealerTableName+" , SALES_"+TableName+" WHERE DEALER_NAME = SALES_CHANNEL1 AND COM_TYPE IN ('MEGALINE' , 'LTE' , 'FTTH') AND DEALER_TYPE = 'S' AND STATUS = 0 GROUP BY SALES_PERSON11"
c.execute(sql)
c.execute("commit")

#ADD SLAB
sql = "ALTER TABLE SALES_COUNT_"+TableName+" ADD SLAB varchar(2)"
c.execute(sql)
c.execute("commit")

#UPDATE SLAB
sql = "UPDATE SALES_COUNT_"+TableName+"SET SLAB = (SELECT SLAB FROM  "+SlabTableName+" WHERE SALES_COUNT  BETWEEN MIN_SALES AND MAX_SALES)"
c.execute(sql)
c.execute("commit")

#ADD COM_STG1
sql = "ALTER TABLE SALES_COUNT_"+TableName+" COM_STG1 NUMBER"
c.execute(sql)
c.execute("commit")

#ADD COM_STG1
sql = "UPDATE SALES_"+TableName+" SET COM_STG1 = (SELECT DISTINCT COMMISSION FROM "+BBTableName+" WHERE UPPER(PACKAGE) = UPPER(BB_PACKAGE_NAME) AND SLAB = (SELECT SLAB FROM SALES_COUNT_"+TableName+" WHERE (DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 ) ) ) WHERE COM_TYPE = 'BB' AND STATUS = 0"
c.execute(sql)
c.execute("commit")

#ADD COM_STG1
sql = "UPDATE SALES_"+TableName+" SET COM_STG1 = (SELECT DISTINCT COMMISSION FROM "+IPTVTableName+" WHERE UPPER(PACKAGE) = UPPER(REPLACE(a.BB_PACKAGE_NAME,' Rental','')) AND SLAB = (SELECT SLAB FROM SALES_COUNT_"+TableName+" WHERE (DEALER_NAME = a.SALES_CHANNEL1 OR DEALER_NAME =  a.SALES_PERSON11 ) ) ) WHERE a.COM_TYPE = 'IPTV' AND STATUS = 0"
c.execute(sql)
c.execute("commit")

#ADD COM_STG1
sql = "UPDATE SALES_"+TableName+" SET COM_STG1 = (SELECT DISTINCT COMMISSION FROM "+BearerTableName+" WHERE PRODUCT = 'FTTH New' AND SLAB = (SELECT SLAB FROM SALES_COUNT_"+TableName+" WHERE (DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 ) ) ) WHERE COM_TYPE = 'FTTH' AND SERO_ORDT_TYPE = 'CREATE' AND STATUS = 0"
c.execute(sql)
c.execute("commit")

#ADD COM_STG1
sql = "UPDATE SALES_"+TableName+" SET COM_STG1 = (SELECT DISTINCT COMMISSION FROM "+BearerTableName+" WHERE PRODUCT = 'FTTH Migration' AND SLAB = (SELECT SLAB FROM SALES_COUNT_"+TableName+" WHERE (DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 ) ) ) WHERE COM_TYPE = 'FTTH' AND SERO_ORDT_TYPE = 'CREATE-UPGRD SAME NO' AND STATUS = 0"
c.execute(sql)
c.execute("commit")

#ADD COM_STG1
sql = "UPDATE SALES_"+TableName+" SET COM_STG1 = (SELECT DISTINCT COMMISSION FROM "+BearerTableName+" WHERE PRODUCT = 'Megaline' AND SLAB = (SELECT SLAB FROM SALES_COUNT_"+TableName+" WHERE (DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 ) ) ) WHERE COM_TYPE = 'MEGALINE' AND STATUS = 0"
c.execute(sql)
c.execute("commit")

#ADD COM_STG1
sql = "UPDATE SALES_"+TableName+" SET COM_STG1 = (SELECT DISTINCT COMMISSION FROM "+BearerTableName+" WHERE PRODUCT = 'LTE' AND SLAB = (SELECT SLAB FROM SALES_COUNT_"+TableName+" WHERE (DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 ) ) ) WHERE COM_TYPE = 'LTE' AND STATUS = 0"
c.execute(sql)
c.execute("commit")

#ADD COM_STG1
sql = "ALTER TABLE SALES_COUNT_"+TableName+" ADD FTTH_STG1 VARCHAR2(20)"
c.execute(sql)
sql = "ALTER TABLE SALES_COUNT_"+TableName+" ADD BB_STG1 VARCHAR2(20)"
c.execute(sql)
sql = "ALTER TABLE SALES_COUNT_"+TableName+" ADD MEGALINE_STG1 VARCHAR2(20)"
c.execute(sql)
sql = "ALTER TABLE SALES_COUNT_"+TableName+" ADD LTE_STG1 VARCHAR2(20)"
c.execute(sql)
sql = "ALTER TABLE SALES_COUNT_"+TableName+" ADD IPTV_STG1 VARCHAR2(20)"
c.execute(sql)
sql = "ALTER TABLE SALES_COUNT_"+TableName+" ADD TOT_STG1 VARCHAR2(20)"
c.execute(sql)
sql = "ALTER TABLE SALES_COUNT_"+TableName+" ADD PAYMRNT_STG1 VARCHAR2(20)"
c.execute(sql)
c.execute("commit")

#ADD COM_STG1
sql = "UPDATE SALES_COUNT_"+TableName+" SET  FTTH_STG1 = (SELECT  SUM(COM_STG1) FROM SALES_"+TableName+" WHERE COM_TYPE = 'FTTH' AND ((DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 )) )"
c.execute(sql)
sql = "UPDATE SALES_COUNT_"+TableName+" SET  LTE_STG1 = (SELECT  SUM(COM_STG1) FROM SALES_"+TableName+" WHERE COM_TYPE = 'LTE' AND ((DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 )) )"
c.execute(sql)
sql = "UPDATE SALES_COUNT_"+TableName+" SET  MEGALINE_STG1 = (SELECT  SUM(COM_STG1) FROM SALES_"+TableName+" WHERE COM_TYPE = 'MEGALINE' AND ((DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 )) )"
c.execute(sql)
sql = "UPDATE SALES_COUNT_"+TableName+" SET  BB_STG1 = (SELECT  SUM(COM_STG1) FROM SALES_"+TableName+" WHERE COM_TYPE = 'BB' AND ((DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 )) )"
c.execute(sql)
sql = "UPDATE SALES_COUNT_"+TableName+" SET  IPTV_STG1 = (SELECT  SUM(COM_STG1) FROM SALES_"+TableName+" WHERE COM_TYPE = 'IPTV' AND ((DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 )) )"
c.execute(sql)
c.execute("commit")

sql = "UPDATE SALES_COUNT_"+TableName+" SET  TOT_STG1 = (SELECT  SUM(COM_STG1) FROM SALES_"+TableName+" WHERE ((DEALER_NAME = SALES_CHANNEL1 OR DEALER_NAME =  SALES_PERSON11 )) )"
c.execute(sql)
c.execute("commit")

sql = "UPDATE SALES_COUNT_"+TableName+" SET  PAYMRNT_STG1 = ROUND(TOT_STG1/2,2) WHERE SLAB <> 'A'"
c.execute(sql)
c.execute("commit")


#exporting data to excel
sql = "SELECT DEALER_NAME FROM "+DealerTableName+" WHERE DEALER_TYPE ='M'";  
c.execute(sql)
for DEALER_NAME in c:
    TableName = str(TBNAME[0])

data = pd.read_sql('SELECT * FROM mytable', conn)
data.to_excel('my_oracle_table.xlsx')
    
c.close()
conn.close()